#ifndef DLLSARJAPORTTI_GLOBAL_H
#define DLLSARJAPORTTI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLSARJAPORTTI_LIBRARY)
#  define DLLSARJAPORTTISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLSARJAPORTTISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLSARJAPORTTI_GLOBAL_H
